# Generated by Django 4.2.7 on 2023-11-25 23:47

from django.db import migrations, models


def extract_external_id(apps, schema_editor):
    Tweet = apps.get_model("tweet_analyzer", "Tweet")  # noqa
    for tweet in Tweet.objects.all():
        external_id = tweet.meta_data["id_str"] or tweet.meta_data["id"]
        tweet.external_id = external_id
        tweet.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="external_id",
            field=models.CharField(default=None, null=True, max_length=24),
            preserve_default=False,
        ),
        migrations.RunPython(
            extract_external_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="tweet",
            name="external_id",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
