# Generated by Django 4.2.7 on 2023-11-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="tweet_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(fields=["user"], name="tweet_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="tweet",
            constraint=models.UniqueConstraint(fields=("tweet_id",), name="tweet_tweet_id_unique_idx"),
        ),
    ]
