# Generated by Django 4.2.7 on 2023-11-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0002_tweet_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="lang",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="raw_content",
            field=models.TextField(null=True),
        ),
    ]
