# Generated by Django 4.2.7 on 2023-11-26 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0002_tweet_tweet_id_tweet_tweet_user_idx_and_more"),
        ("tweet_analyzer", "0004_tweet_sanitized_content"),
    ]

    operations = []
