# Generated by Django 4.2.7 on 2023-11-26 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0005_merge_20231126_2323"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tweet",
            name="tweet_tweet_id_unique_idx",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="tweet_id",
        ),
    ]
