# Generated by Django 4.2.7 on 2023-11-27 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0007_rename_external_id_tweet_tweet_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative"), ("neutral", "Neutral")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "model",
                    models.CharField(
                        choices=[("langchain_gpt4", "Langchain Gpt4"), ("langchain_gpt35", "Langchain Gpt35")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("prompt", models.TextField(null=True)),
                (
                    "frame",
                    models.CharField(
                        choices=[("m15", "M15"), ("m30", "M30"), ("m60", "M60")], max_length=8, null=True
                    ),
                ),
                ("frame_last_tweet_id", models.CharField(max_length=24, null=True)),
                (
                    "prompt_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tweet_analyzer.prompttemplate"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tweet_analyzer.influencer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TweetSentiment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "sentiment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tweet_analyzer.sentiment"),
                ),
                ("tweet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tweet_analyzer.tweet")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tweet"], name="tweet_senti_tweet_idx"),
                    models.Index(fields=["sentiment"], name="tweet_senti_senti_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sentiment",
            index=models.Index(fields=["user"], name="senti_user_idx"),
        ),
        migrations.AddIndex(
            model_name="sentiment",
            index=models.Index(fields=["prompt_template"], name="senti_prompt_templ_idx"),
        ),
    ]
