# Generated by Django 4.2.7 on 2023-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0008_prompttemplate_sentiment_tweetsentiment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentiment",
            name="frame_last_tweet_id",
        ),
        migrations.AddField(
            model_name="sentiment",
            name="token",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
