# Generated by Django 4.2.7 on 2023-12-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0001_initial"),
        ("tweet_analyzer", "0009_remove_sentiment_frame_last_tweet_id_sentiment_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="mentioned_tokens",
            field=models.ManyToManyField(to="crypto.token"),
        ),
    ]
