# Generated by Django 4.2.7 on 2023-12-05 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0010_tweet_mentioned_tokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-date"]},
        ),
    ]
