# Generated by Django 4.2.7 on 2023-12-05 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0011_alter_tweet_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tweetsentiment",
            name="tweet_senti_tweet_idx",
        ),
        migrations.RemoveIndex(
            model_name="tweetsentiment",
            name="tweet_senti_senti_idx",
        ),
        migrations.RemoveField(
            model_name="tweetsentiment",
            name="sentiment",
        ),
        migrations.AddField(
            model_name="tweetsentiment",
            name="category",
            field=models.CharField(default="positive", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweetsentiment",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=90,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tweetsentiment",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sentiments", to="tweet_analyzer.tweet"
            ),
        ),
    ]
