# Generated by Django 4.2.7 on 2023-12-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0013_prompttemplate_created_prompttemplate_modified_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tweet",
            name="tweet_user_idx",
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(fields=["-date"], name="tweet_analy_date_099c27_idx"),
        ),
    ]
