# Generated by Django 4.2.7 on 2023-12-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0014_remove_tweet_tweet_user_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tweetsentiment",
            index=models.Index(fields=["category"], name="tweet_analy_categor_acde37_idx"),
        ),
    ]
