# Generated by Django 4.2.7 on 2023-12-12 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0010_periodictaskrun"),
        ("tweet_analyzer", "0015_tweetsentiment_tweet_analy_categor_acde37_idx"),
    ]

    operations = []
