# Generated by Django 4.2.7 on 2023-12-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0016_merge_20231212_2027"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sentiment",
            name="senti_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="sentiment",
            name="senti_prompt_templ_idx",
        ),
        migrations.RenameIndex(
            model_name="periodictaskrun",
            new_name="tweet_analy_name_9a351f_idx",
            old_name="periodic_task_run_name_idx",
        ),
        migrations.AlterField(
            model_name="periodictaskrun",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="periodictaskrun",
            name="last_run_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweets", to="tweet_analyzer.influencer"
            ),
        ),
    ]
