# Generated by Django 4.2.7 on 2023-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0017_remove_sentiment_senti_user_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetsentiment",
            name="category",
            field=models.CharField(
                choices=[
                    ("very negative", "Very Negative"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                    ("positive", "Positive"),
                    ("very positive", "Very Positive"),
                ],
                max_length=32,
            ),
        ),
    ]
