# Generated by Django 4.2.7 on 2023-12-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0018_alter_tweetsentiment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetsentiment",
            name="explain",
            field=models.TextField(default=None, null=True),
        ),
    ]
