# Generated by Django 4.2.7 on 2023-12-17 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0018_alter_tweetsentiment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictaskrun",
            name="every",
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="periodictaskrun",
            name="period",
            field=models.CharField(max_length=24, null=True),
        ),
    ]
