# Generated by Django 4.2.7 on 2023-12-21 22:37

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0019_tweetsentiment_explain"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTrendAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("trend", models.CharField(max_length=32)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("period", models.DurationField()),
                ("interval", models.DurationField()),
                ("plot_image", models.ImageField(upload_to="plots")),
                ("meta_data", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_trend_analyses",
                        to="tweet_analyzer.tweet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price Trend Analyses",
            },
        ),
    ]
