# Generated by Django 4.2.7 on 2023-12-27 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0019_periodictaskrun_every_periodictaskrun_period"),
        ("tweet_analyzer", "0020_pricetrendanalysis"),
    ]

    operations = []
