# Generated by Django 4.2.7 on 2023-12-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0021_merge_20231227_0355"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencer",
            name="display_name",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="profile_banner_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
