# Generated by Django 4.2.7 on 2023-12-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet_analyzer", "0022_influencer_display_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("username", models.TextField(db_collation="NOCASE,", primary_key=True, serialize=False)),
                ("password", models.TextField()),
                ("email", models.TextField()),
                ("email_password", models.TextField()),
                ("user_agent", models.TextField()),
                ("active", models.BooleanField()),
                ("locks", models.TextField()),
                ("headers", models.TextField()),
                ("cookies", models.TextField()),
                ("proxy", models.TextField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("stats", models.TextField()),
                ("last_used", models.TextField(blank=True, null=True)),
                ("field_tx", models.TextField(blank=True, db_column="_tx", null=True)),
            ],
            options={
                "db_table": "accounts",
                "managed": False,
            },
        ),
    ]
